// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

void GUI::cb_DBG_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_DBG(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_DBG_i(o,v);
}

void GUI::cb_NewButton_i(Fl_Return_Button*, void*) {
  NewButton_cb();
}
void GUI::cb_NewButton(Fl_Return_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_NewButton_i(o,v);
}
void GUI::pano_demo_button_i(Fl_Button*, void*) {
  PanoDemo();
}
void GUI::pano_demo_button(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->pano_demo_button_i(o,v);
}
void GUI::izb_demo_button_i(Fl_Button*, void*) {
  IZBDemo();
}
void GUI::izb_demo_button(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->izb_demo_button_i(o,v);
}

void GUI::reg_demo_button_i(Fl_Button*, void*) {
  RegShadowDemo();
}
void GUI::reg_demo_button(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->reg_demo_button_i(o,v);
}
void GUI::gps_demo_button_i(Fl_Button*, void*) {
  GPShadowDemo();
}
void GUI::gps_demo_button(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->gps_demo_button_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(300, 300, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(15, 15, 95, 40, "DBG");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_DBG);
    } // Fl_Button* o
    { Fl_Return_Button* o = new Fl_Return_Button(15, 60, 200, 50, "Water reflection demo");
      o->callback((Fl_Callback*)cb_NewButton);
    } // Fl_Return_Button* o

    { Fl_Button* o = new Fl_Button(15, 120, 95, 50, "Pano Demo");
      o->callback((Fl_Callback*)pano_demo_button);
    } 
    { Fl_Button* o = new Fl_Button(15, 180, 95, 50, "IZB Demo");
      o->callback((Fl_Callback*)izb_demo_button);
    } 
    { Fl_Button* o = new Fl_Button(110, 180, 95, 50, "Regular SM");
      o->callback((Fl_Callback*)reg_demo_button);
    } 
    { Fl_Button* o = new Fl_Button(15, 240, 95, 50, "Gp shadow");
      o->callback((Fl_Callback*)gps_demo_button);
    } 
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::NewButton_cb() {
  scene->RenderReflectionDemo();
    scene->SetMode(5);
}

void GUI::PanoDemo() {
    scene->RenderJustPanorama();
    scene->SetMode(3);
}

void GUI::IZBDemo() {
    scene->RenderShadowScene(1);
    scene->SetMode(1);
}

void GUI::RegShadowDemo() {
    scene->RenderShadowScene(0);
    scene->SetMode(2);
}

void GUI::GPShadowDemo() {
    scene->RenderGroundPlaneShadows();
    scene->SetMode(4);
}
